global class LeadWrapperClass {
    public String FirstName { get; set; }
    public String MiddleName { get; set; }
    public String LastName { get; set; }
    public String City { get; set; }
    public String PostalCode { get; set; }
    public String Region { get; set; }
    public String MobilePhone { get; set; }
    public String LandlinePhone { get; set; }
    public String OtherPhone { get; set; }
    public String ParentPhone { get; set; }
    public Date DOB { get; set; }
    public String StudentEmail1 { get; set; }
    public String StudentEmail2 { get; set; }
    public String ParentEmail { get; set; }
    public String InvoiceEmail { get; set; }
    public String TritonId { get; set; }
    public String Activity { get; set; }
    public String Program { get; set; }
    public String Product { get; set; }
    public String MarketCode { get; set; }
    public DateTime ActivityDate { get; set; }
    public String Street { get; set; }
    public String CountryCode { get; set; }
    public String State { get; set; }


}